version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "clap"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
